# Automatically build the project and run any configured tests for every push
# and submitted pull request. This provides a first line of defence against
# bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Install advancecomp and strip-nondeterminism
        run: sudo apt-get install advancecomp strip-nondeterminism -y
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Run strip-nondeterminism on built .jar files
        run: strip-nondeterminism build/libs/*.jar
      - name: Run advzip (-i 99) on built .jar files
        run: advzip --shrink-insane -kzi 99 -p build/libs/*.jar
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '1.8' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
